### ISSUE TITLE
Benchmarking method

### ISSUE THREAD

**Issue by s3afroze** [awslabs/sagemaker-battlesnake-ai#15]
Hi,
Where is the matrix saved so that I could benchmark the new model?

Thanks,

Shahzeb

**Comment by jonomon** [comment]
Hi Shahzeb,

Which matrix are you referring to?

**Comment by s3afroze** [comment]
Hi Jonathan!
That was the wrong question on my end - I was interested in knowing if the training information is saved anywhere so that I could average it out for comparison with the newer models?

btw just wanted to say, thank you so much for sharing a cool project like this!

**Comment by jonomon** [comment]
Hi Shahzeb,

Thank you for your kind words.

If you are training on SageMaker, you can navigate to your training job. You should see plots of the metrics in the Monitor section. Similar to the screenshot below. 

![Screen Shot 2020-04-10 at 10 53 01 AM](https://user-images.githubusercontent.com/1509369/79011718-77a62f00-7b19-11ea-8fe4-5f7e9aa7bb70.png)

**Comment by s3afroze** [comment]
Thank you : )!
