### ISSUE TITLE
MXBoard Integration in the Example is Broken

### ISSUE THREAD

**Issue by kshahzada** [awslabs/sagemaker-battlesnake-ai#17]
**Summary of Bug**
When you try to use the Writer param in examples/train.py so you can view the training process with MXBoard/Tensorboard, the program crashes.

**Steps to reproduce:**
1. Run: `python3 train.py --should_render --writer --run_name test_1 --render_steps 100`
2. Notice ->
> Traceback (most recent call last):
>   File "train.py", line 193, in <module>
>     run(seed, args)
>   File "train.py", line 42, in run
>     writer = SummaryWriter("logs/{}-seed{}".format(run_name, seed), verbose=False)
> NameError: name 'run_name' is not defined
and/or 
> Traceback (most recent call last):
>   File "train.py", line 193, in <module>
>     run(seed, args)
>   File "train.py", line 91, in run
>     args.writer, args.print_progress)
>   File "/Users/Kshahzada/Documents/GitHub/sagemaker-battlesnake-ai/TrainingEnvironment/examples/dqn_run.py", line 85, in trainer
>     writer.add_scalar("rewards_{}".format(i), score[i], i_episode)
> AttributeError: 'bool' object has no attribute 'add_scalar'

**Expected Output**
Should start creating logs for Tensorboard to use.

**Actual Output**
Crashes.

**Comment by kshahzada** [comment]
^^^ I've proposed a functioning fix

**Comment by jonomon** [comment]
Merged with https://github.com/awslabs/sagemaker-battlesnake-ai/pull/18
