### ISSUE TITLE
Add tags to resources to assist in tracking costs.

### ISSUE THREAD

**Issue by bmitch** [awslabs/sagemaker-battlesnake-ai#19]
I was wondering if this project would be open to having a tag (or tags) added to the CloudFormation template resource in order to help users track the costs.

If so I'd be up for submitting a PR. I am relatively new to CloudFormation templates but feel this would be a good starting point. Thank you.

**Comment by xavierraffin** [comment]
This is a great idea Bill.
I am about to publish an update of the project (with updated CF).
So hold on until I do and yes your PR will be welcome then

**Comment by bmitch** [comment]
Great thank you @xavierraffin !

**Comment by xavierraffin** [comment]
I just pushed the version 2.0.0
I still have some test to run (we have dependency to Github url on the code itself) but you can start coding.
Closing this and waiting to see your PR!
thanks again for raising this
