### ISSUE TITLE
Missing setup.sh

### ISSUE THREAD

**Issue by vishaalkapoor** [awslabs/sagemaker-battlesnake-ai#8]
It looks like there is some code that no longer is needed. In SageMakerModelTraining
```
# only run from SageMaker notebook instance
if local_mode:
    !/bin/bash ./setup.sh
```
gives 
```/bin/bash: ./setup.sh: No such file or directory```
when in local_mode.

**Comment by jonomon** [comment]
https://github.com/awslabs/sagemaker-battlesnake-ai/pull/9
